Rework model
furaihan/fp-pemrog-lanjut pull request #6
Opened 2022-12-07 10:48 UTC by pijarpahlawan

2022-12-07 18:27 UTC, furaihan requested changes
ada project coba itu kayaknya, hapus dulu

2022-12-07 18:27 UTC, furaihan commented on PinusPengger.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "coba", "..\coba\coba.csproj", "{B1E744CF-F9CD-4195-BD23-2D304D3C1A2D}"
apa ini ges?

2022-12-07 18:27 UTC, furaihan commented on PinusPengger.sln
> +		{B1E744CF-F9CD-4195-BD23-2D304D3C1A2D}.Release|Any CPU.Build.0 = Release|Any CPU
??

2022-12-08 00:41 UTC, pijarpahlawan commented on PinusPengger.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "coba", "..\coba\coba.csproj", "{B1E744CF-F9CD-4195-BD23-2D304D3C1A2D}"
gatau itu tak insertke tok. tiba tiba muncul di slnnya

2022-12-08 00:47 UTC, pijarpahlawan commented on PinusPengger.sln
> +		{B1E744CF-F9CD-4195-BD23-2D304D3C1A2D}.Release|Any CPU.Build.0 = Release|Any CPU
itu abis dimerge dihapus aja dari sana

2022-12-08 22:34 UTC, merged